---
  - include: "{{nfs_mode}}.yaml"

  - name: Lock NFS ports
    lineinfile:
      dest: /etc/sysconfig/nfs
      regexp: "^#{{item}}"
      line: "{{item}}"
      state: present
    with_items:
    - 'LOCKD_TCPPORT=32803'
    - 'LOCKD_UDPPORT=32769'
    - 'MOUNTD_PORT=892'
    notify:
     - restart rpcbind
     - restart nfs    
